### ISSUE TITLE
Sporadic "Assertion `ptaskData->inMLHeap' failed" running test suite for interpreted version

### ISSUE THREAD

**Issue by jrtc27** [polyml/polyml#52]
Running the test suite on the interpreted version sometimes gives ``poly: processes.cpp:768: void Processes::ThreadReleaseMLMemoryWithSchedLock(TaskData*): Assertion `ptaskData->inMLHeap' failed.``. It seems to be when `make_exn` in `IntTaskData::InitStackFrame` needs to do a GC, but `inMLHeap` is currently false as the task data isn't yet in use. Reverting 1e230f1c60ac39b236d89784899c5fd003360198 makes it no longer reproducible (was previously ~50% reproducible, and the test suite now passes 5/5 times). Stack trace:
```
#0  0x00007ffff6b37478 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007ffff6b388fa in __GI_abort () at abort.c:89
#2  0x00007ffff6b303a7 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0xaf1fb9 "ptaskData->inMLHeap", file=file@entry=0xaf1fa9 "processes.cpp", 
    line=line@entry=768, 
    function=function@entry=0xaf2320 <Processes::ThreadReleaseMLMemoryWithSchedLock(TaskData*)::__PRETTY_FUNCTION__> "void Processes::ThreadReleaseMLMemoryWithSchedLock(TaskData*)")
    at assert.c:92
#3  0x00007ffff6b30452 in __GI___assert_fail (assertion=assertion@entry=0xaf1fb9 "ptaskData->inMLHeap", file=file@entry=0xaf1fa9 "processes.cpp", line=line@entry=768, 
    function=function@entry=0xaf2320 <Processes::ThreadReleaseMLMemoryWithSchedLock(TaskData*)::__PRETTY_FUNCTION__> "void Processes::ThreadReleaseMLMemoryWithSchedLock(TaskData*)")
    at assert.c:101
#4  0x00000000004054fe in Processes::ThreadReleaseMLMemoryWithSchedLock (taskData=0x7fffec013480, this=0xd26e80 <processesModule>) at processes.cpp:768
#5  0x0000000000aa9ab0 in Processes::ThreadReleaseMLMemoryWithSchedLock (taskData=<optimized out>, this=<optimized out>) at processes.cpp:768
#6  Processes::MakeRootRequest (this=0xd26e80 <processesModule>, taskData=0x7fffec013480, request=0x7ffff42fdba0) at processes.cpp:785
#7  0x0000000000acb194 in QuickGC (taskData=taskData@entry=0x7fffec013480, wordsRequiredToAllocate=wordsRequiredToAllocate@entry=3) at gc.cpp:389
#8  0x0000000000aa904b in Processes::FindAllocationSpace (this=0xd26e80 <processesModule>, taskData=0x7fffec013480, words=3, alwaysInSeg=false) at processes.cpp:876
#9  0x0000000000aad5a5 in alloc (taskData=taskData@entry=0x7fffec013480, data_words=data_words@entry=2, flags=flags@entry=1) at run_time.cpp:163
#10 0x0000000000adbae7 in C_string_to_Poly (mdTaskData=mdTaskData@entry=0x7fffec013480, buffer=0xaf2d8c "Overflow", buffLen=<optimized out>, buffLen@entry=18446744073709551615)
    at polystring.cpp:75
#11 0x0000000000aad77b in make_exn (taskData=taskData@entry=0x7fffec013480, id=id@entry=5, arg=0x7fffec0247f0) at run_time.cpp:271
#12 0x0000000000ab3bb6 in IntTaskData::InitStackFrame (this=0x7fffec013480, parentTask=<optimized out>, proc=<optimized out>, arg=<optimized out>) at interpret.cpp:209
#13 0x0000000000aaabcb in Processes::ForkThread (this=this@entry=0xd26e80 <processesModule>, taskData=taskData@entry=0xd69590, threadFunction=0xd696a0, args=args@entry=0x0, flags=..., 
    flags@entry=..., stacksize=..., stacksize@entry=...) at processes.cpp:1453
#14 0x0000000000aab018 in Processes::ThreadDispatch (this=0xd26e80 <processesModule>, taskData=0xd69590, args=<optimized out>, code=<optimized out>) at processes.cpp:523
#15 0x0000000000ab49f9 in CallIO2 (taskData=taskData@entry=0xd69590, ioFun=0xaab5c0 <ThreadDispatch(TaskData*, SaveVecEntry*, SaveVecEntry*)>) at interpret.cpp:1507
#16 0x0000000000ab753f in IntTaskData::EnterPolyCode (this=0xd69590) at interpret.cpp:1792
#17 0x0000000000aaa4a0 in NewThreadFunction (parameter=0xd69590) at processes.cpp:1128
#18 0x00007ffff7bc5454 in start_thread (arg=0x7ffff42fe700) at pthread_create.c:334
#19 0x00007ffff6becedd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by dcjm** [comment]
I've committed a change [https://github.com/polyml/polyml/commit/feadb1580c1aeeb2215f4c35e0969e6b8883f1d0](https://github.com/polyml/polyml/commit/feadb1580c1aeeb2215f4c35e0969e6b8883f1d0) that should deal with this.  Could you recheck?  I haven't been able to reproduce the original problem.

**Comment by jrtc27** [comment]
Passes 5/5 test suite runs, where before it failed ~50% of the time. Closing; thanks!
